package com.demo.springbootdemo.dao;

import com.demo.springbootdemo.pojo.DemoTable;
import com.demo.springbootdemo.pojo.DemoTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    long countByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int deleteByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int insert(DemoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int insertSelective(DemoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    List<DemoTable> selectByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    DemoTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DemoTable record, @Param("example") DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DemoTable record, @Param("example") DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DemoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DemoTable record);
}